name: smart_home_dashboard
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^1.2.2
  flutter_icons: ^1.1.0
  simple_animations: ^2.2.1
  fl_chart: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/logo.png
    - assets/icons/home.png
    - assets/icons/chart.png
    - assets/icons/lamp.png
    - assets/icons/location.png
    - assets/icons/logout.png
    - assets/icons/security.png
    - assets/icons/user_group.png
    - assets/icons/cloud.png
    - assets/icons/drop.png
    - assets/icons/thermometer.png
    - assets/icons/rain_drop.png
    - assets/icons/all_lights_active.png
    - assets/icons/all_lights_inactive.png
    - assets/icons/all_lights_selected.png
    - assets/icons/ac_active.png
    - assets/icons/ac_inactive.png
    - assets/icons/ac_selected.png
    - assets/icons/refrigerator_active.png
    - assets/icons/refrigerator_inactive.png
    - assets/icons/refrigerator_selected.png
    - assets/icons/flash_active.png
    - assets/icons/flash_inactive.png
    - assets/icons/flash_selected.png
    - assets/icons/active_notifications.png
    - assets/icons/female_profile_avatar.png
    - assets/icons/notifications.png
    - assets/icons/settings.png
    - assets/icons/music.png
    - assets/icons/router.png
    - assets/icons/refrigerator.png
    - assets/avatars/dad.png
    - assets/avatars/jasica.png
    - assets/avatars/mom.png
    - assets/avatars/nariya.png
    - assets/avatars/riya.png
    - assets/images/welcome_background.png
